version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: kramdown
    versions:
    - 2.3.1
  - dependency-name: govuk_tech_docs
    versions:
    - 2.1.0
    - 2.1.1
    - 2.2.0
    - 2.2.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
